server:
  port: 8202
spring:
  application:
    name: smart-nacos-user-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://smart-eureka:smart-eureka-pwd@localhost:8001/eureka/