server:
  port: 8302
spring:
  application:
    name: smart-hystrix-user
eureka:
  client:
    service-url:
      defaultZone: http://smart-eureka:smart-eureka-pwd@localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点（hystrix-dashboard使用）
#定义服务访问地址（以服务名作为URI），业务层使用
service-url:
  user-service: http://user-service

