server:
  port: 8001 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
  security:           #设置一个简单的Security账户密码 (https://juejin.im/post/5d78cd53f265da03d55e8351)
    user:
      name: smart-eureka
      password: smart-eureka-pwd
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
  server:
    enable-self-preservation: false #关闭保护模式